### ISSUE TITLE
Request to add documentation for installing this plugin

### ISSUE THREAD

**Issue by Danendra10** [ErickKramer/nvim-ros2#1]
I'm new to nvim, please help me configure this plugins, i'm also having an issue like the photo below, help meeee

I'm using nvim 0.10.0, ubuntu 22, ros humble, clangd

![image](https://github.com/ErickKramer/nvim-ros2/assets/72090618/7a2975f4-c7d1-48e5-b11c-b16e5cf9fc2f)
![image](https://github.com/ErickKramer/nvim-ros2/assets/72090618/be05ad5b-d831-4633-886a-15c004529497)

**Comment by ErickKramer** [comment]
Hi,
There is not much configuration needed to get this plugin working. I would advise to use the lazy.nvim approach

```lua
{
	"ErickKramer/nvim-ros2",
	dependencies = {
		"nvim-lua/plenary.nvim",
		"nvim-telescope/telescope.nvim",
		"nvim-treesitter/nvim-treesitter",
	},
    opts = {
        -- Add any custom options here
			autocmds = true,
			telescope = true,
			treesitter = true,
    }
},
```

That's what I am using also in the neovim configuration targeted towards ROS 2 development https://github.com/ErickKramer/ros2-with-neovim/blob/0a0697ee8071beb956c8bff12faf51ff925252d3/.config/nvim/init.lua#L1267

Now, regarding your error, I am almost certain that the root cause is the missing `compile_commands.json` and/or using the wrong compiler while building your ROS package.

The very first compilation for a clean C++ package is somewhat cumbersome. But, you can do something like 

1. Create a package using the `ros2 pkg create --build-type ament_cmake <package_name>`
2. Create some placeholder C++ and make sure you configure your CMakeLists.txt file

```cpp
#include <chrono>
#include <functional>
#include <memory>
#include <string>

#include "rclcpp/rclcpp.hpp"
#include "std_msgs/msg/string.hpp"

using namespace std::chrono_literals;

/* This example creates a subclass of Node and uses std::bind() to register a
* member function as a callback from the timer. */

class MinimalPublisher : public rclcpp::Node
{
  public:
    MinimalPublisher()
    : Node("minimal_publisher"), count_(0)
    {
      publisher_ = this->create_publisher<std_msgs::msg::String>("topic", 10);
      timer_ = this->create_wall_timer(
      500ms, std::bind(&MinimalPublisher::timer_callback, this));
    }

  private:
    void timer_callback()
    {
      auto message = std_msgs::msg::String();
      message.data = "Hello, world! " + std::to_string(count_++);
      RCLCPP_INFO(this->get_logger(), "Publishing: '%s'", message.data.c_str());
      publisher_->publish(message);
    }
    rclcpp::TimerBase::SharedPtr timer_;
    rclcpp::Publisher<std_msgs::msg::String>::SharedPtr publisher_;
    size_t count_;
};

int main(int argc, char * argv[])
{
  rclcpp::init(argc, argv);
  rclcpp::spin(std::make_shared<MinimalPublisher>());
  rclcpp::shutdown();
  return 0;
}
```

```cmake
find_package(rclcpp CONFIG REQUIRED)
add_executable(${PROJECT_NAME}_node src/<YOUR_FILE>.cpp)
install(
  TARGETS ${PROJECT_NAME}_node
  DESTINATION lib/${PROJECT_NAME}
)
```

4. Compile your workspace using the proper compiler and cmake flags   

    ```console
    CC=clang CXX=clang++ colcon build --symlink-install --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    ```
5. Then, you should be able to get clang working normally.

Hopefully, this can help you to get your setup working

**Comment by Danendra10** [comment]
Thank you so much, you're the first most fast responded person on the issues that I've been published

Right now, I'm resolving it by adding env variable $CPATH, i'll give it a try with your solution
